// The Kickstand fleet.
//
// Demo data, no database. Listing windows are stored as day offsets and resolved
// against a caller-supplied "today", so the site never drifts into showing a fleet
// that was only bookable in the month it was deployed.

import type { Bike, Category, DateRange, ISODate } from './types';
import { addDays } from './pricing.ts';

type Seed = Omit<Bike, 'listed' | 'booked'> & {
  /** Day offsets from today for the window the owner has released. */
  listedFrom: number;
  listedTo: number;
  /** Day-offset pairs already taken by other riders. */
  bookedOffsets: [number, number][];
};

const SEEDS: Seed[] = [
  {
    id: 'stripe-765',
    make: 'Triumph',
    model: 'Street Triple 765 RS',
    year: 2023,
    category: 'Naked',
    displacement: 765,
    power: 128,
    weight: 189,
    seatHeight: 826,
    licence: 'A',
    city: 'London',
    pickupArea: 'Hackney Wick',
    pricePerDay: 89,
    weeklyDiscount: 0.15,
    monthlyDiscount: 0.32,
    deposit: 400,
    milesPerDay: 150,
    extraMileRate: 0.35,
    rating: 4.94,
    trips: 37,
    instantBook: true,
    host: { name: 'Dan H.', since: 2022, topHost: true },
    listedFrom: -4,
    listedTo: 45,
    bookedOffsets: [[3, 7]],
    included: ['Optimate charger', 'Second key', 'Top box mount'],
    note: 'Serviced at 8,400 miles. Quickshifter is set up for the road, not the track — please treat it that way.'
  },
  {
    id: 'cb500x',
    make: 'Honda',
    model: 'CB500X',
    year: 2022,
    category: 'Adventure',
    displacement: 471,
    power: 47,
    weight: 199,
    seatHeight: 830,
    licence: 'A2',
    city: 'Manchester',
    pickupArea: 'Ancoats',
    pricePerDay: 52,
    weeklyDiscount: 0.18,
    monthlyDiscount: 0.35,
    deposit: 250,
    milesPerDay: 175,
    extraMileRate: 0.3,
    rating: 4.88,
    trips: 61,
    instantBook: true,
    host: { name: 'Priya S.', since: 2021, topHost: true },
    listedFrom: -10,
    listedTo: 60,
    bookedOffsets: [[12, 15]],
    included: ['Heated grips', 'Crash bars', 'USB charger'],
    note: 'The bike I learned on and never sold. Ideal first A2 rental — forgiving, light, and it will not embarrass you.'
  },
  {
    id: 'monster-937',
    make: 'Ducati',
    model: 'Monster 937',
    year: 2023,
    category: 'Naked',
    displacement: 937,
    power: 111,
    weight: 188,
    seatHeight: 820,
    licence: 'A',
    city: 'Brighton',
    pickupArea: 'Kemptown',
    pricePerDay: 95,
    weeklyDiscount: 0.12,
    monthlyDiscount: 0.28,
    deposit: 500,
    milesPerDay: 125,
    extraMileRate: 0.4,
    rating: 4.97,
    trips: 24,
    instantBook: false,
    host: { name: 'Marco V.', since: 2023, topHost: false },
    listedFrom: 2,
    listedTo: 38,
    bookedOffsets: [],
    included: ['Termignoni cans', 'Tail tidy', 'Paddock stand'],
    note: 'Kept immaculate and garaged. I approve requests personally — tell me where you are heading.'
  },
  {
    id: 'r1250gsa',
    make: 'BMW',
    model: 'R 1250 GS Adventure',
    year: 2021,
    category: 'Adventure',
    displacement: 1254,
    power: 134,
    weight: 268,
    seatHeight: 890,
    licence: 'A',
    city: 'Edinburgh',
    pickupArea: 'Leith',
    pricePerDay: 115,
    weeklyDiscount: 0.2,
    monthlyDiscount: 0.38,
    deposit: 600,
    milesPerDay: 200,
    extraMileRate: 0.32,
    rating: 4.91,
    trips: 44,
    instantBook: true,
    host: { name: 'Fiona M.', since: 2020, topHost: true },
    listedFrom: -1,
    listedTo: 52,
    bookedOffsets: [[-1, 2]],
    included: ['Full aluminium luggage', 'Tank bag', 'Garmin mount', 'Heated seat'],
    note: 'Built for the NC500 and it has done it four times. Tall — 890mm seat, so bring some inside leg.'
  },
  {
    id: 'interceptor-650',
    make: 'Royal Enfield',
    model: 'Interceptor 650',
    year: 2023,
    category: 'Classic',
    displacement: 648,
    power: 47,
    weight: 202,
    seatHeight: 804,
    licence: 'A',
    city: 'Bristol',
    pickupArea: 'Stokes Croft',
    pricePerDay: 45,
    weeklyDiscount: 0.16,
    monthlyDiscount: 0.3,
    deposit: 200,
    milesPerDay: 150,
    extraMileRate: 0.28,
    rating: 4.85,
    trips: 53,
    instantBook: true,
    host: { name: 'Owen T.', since: 2022, topHost: false },
    listedFrom: -6,
    listedTo: 70,
    bookedOffsets: [],
    included: ['Bar-end mirrors', 'Cafe seat', 'Disc lock'],
    note: 'Cheapest way to have a genuinely good time on a B-road. Sounds far more expensive than it is.'
  },
  {
    id: 'mt-07',
    make: 'Yamaha',
    model: 'MT-07',
    year: 2022,
    category: 'Naked',
    displacement: 689,
    power: 72,
    weight: 184,
    seatHeight: 805,
    licence: 'A',
    city: 'Leeds',
    pickupArea: 'Holbeck',
    pricePerDay: 58,
    weeklyDiscount: 0.15,
    monthlyDiscount: 0.3,
    deposit: 300,
    milesPerDay: 150,
    extraMileRate: 0.3,
    rating: 4.9,
    trips: 68,
    instantBook: true,
    host: { name: 'Sam K.', since: 2021, topHost: true },
    listedFrom: -2,
    listedTo: 40,
    bookedOffsets: [
      [5, 9],
      [20, 23]
    ],
    included: ['Tail pack', 'Phone mount', 'Spare visor'],
    note: 'Most-booked bike in Leeds three summers running. New Michelin Road 6s at the front.'
  },
  {
    id: 'ninja-400',
    make: 'Kawasaki',
    model: 'Ninja 400',
    year: 2021,
    category: 'Sport',
    displacement: 399,
    power: 45,
    weight: 168,
    seatHeight: 785,
    licence: 'A2',
    city: 'Birmingham',
    pickupArea: 'Digbeth',
    pricePerDay: 42,
    weeklyDiscount: 0.18,
    monthlyDiscount: 0.34,
    deposit: 200,
    milesPerDay: 150,
    extraMileRate: 0.28,
    rating: 4.82,
    trips: 39,
    instantBook: true,
    host: { name: 'Aisha R.', since: 2022, topHost: false },
    listedFrom: -8,
    listedTo: 34,
    bookedOffsets: [],
    included: ['Tank grips', 'Disc lock', 'Cover'],
    note: 'A2-legal and low enough for shorter riders. Great first sports bike, cheap on fuel.'
  },
  {
    id: 'fatbob-114',
    make: 'Harley-Davidson',
    model: 'Fat Bob 114',
    year: 2020,
    category: 'Cruiser',
    displacement: 1868,
    power: 92,
    weight: 306,
    seatHeight: 710,
    licence: 'A',
    city: 'Glasgow',
    pickupArea: 'Finnieston',
    pricePerDay: 105,
    weeklyDiscount: 0.14,
    monthlyDiscount: 0.26,
    deposit: 500,
    milesPerDay: 125,
    extraMileRate: 0.38,
    rating: 4.86,
    trips: 21,
    instantBook: false,
    host: { name: 'Callum B.', since: 2023, topHost: false },
    listedFrom: 4,
    listedTo: 44,
    bookedOffsets: [],
    included: ['Screamin Eagle intake', 'Sissy bar', 'Saddlebags'],
    note: 'Low seat, huge torque, no interest in corners. Perfect for the coast road to Loch Lomond.'
  },
  {
    id: 'zero-srf',
    make: 'Zero',
    model: 'SR/F',
    year: 2023,
    category: 'Electric',
    displacement: null,
    power: 110,
    weight: 227,
    seatHeight: 787,
    licence: 'A',
    city: 'London',
    pickupArea: 'Peckham',
    pricePerDay: 78,
    weeklyDiscount: 0.17,
    monthlyDiscount: 0.33,
    deposit: 400,
    milesPerDay: 110,
    extraMileRate: 0.3,
    rating: 4.93,
    trips: 29,
    instantBook: true,
    host: { name: 'Noor A.', since: 2022, topHost: true },
    listedFrom: -3,
    listedTo: 48,
    bookedOffsets: [[1, 3]],
    included: ['Rapid charge cable', 'ULEZ exempt', 'Top box'],
    note: 'Silent, violent, and free to run in the congestion zone. 140 miles of city range, less if you enjoy yourself.'
  },
  {
    id: 'duke-890r',
    make: 'KTM',
    model: '890 Duke R',
    year: 2022,
    category: 'Naked',
    displacement: 889,
    power: 119,
    weight: 166,
    seatHeight: 834,
    licence: 'A',
    city: 'Manchester',
    pickupArea: 'Chorlton',
    pricePerDay: 86,
    weeklyDiscount: 0.13,
    monthlyDiscount: 0.29,
    deposit: 450,
    milesPerDay: 150,
    extraMileRate: 0.36,
    rating: 4.89,
    trips: 33,
    instantBook: false,
    host: { name: 'Jonty P.', since: 2023, topHost: false },
    listedFrom: -5,
    listedTo: 36,
    bookedOffsets: [[16, 19]],
    included: ['Akrapovic slip-on', 'Quickshifter', 'Track mode unlocked'],
    note: 'Sharp, light, and completely unforgiving of ham fists. Experienced riders only, please.'
  },
  {
    id: 'v7-stone',
    make: 'Moto Guzzi',
    model: 'V7 Stone',
    year: 2021,
    category: 'Classic',
    displacement: 853,
    power: 65,
    weight: 218,
    seatHeight: 780,
    licence: 'A',
    city: 'Bristol',
    pickupArea: 'Bedminster',
    pricePerDay: 62,
    weeklyDiscount: 0.15,
    monthlyDiscount: 0.3,
    deposit: 300,
    milesPerDay: 150,
    extraMileRate: 0.3,
    rating: 4.95,
    trips: 18,
    instantBook: true,
    host: { name: 'Elena D.', since: 2023, topHost: false },
    listedFrom: -7,
    listedTo: 58,
    bookedOffsets: [],
    included: ['Leather panniers', 'Chrome mirrors', 'Cover'],
    note: 'Transverse V-twin that rocks at idle and pulls like a train. The most charming thing on the list.'
  },
  {
    id: 'tuono-660',
    make: 'Aprilia',
    model: 'Tuono 660',
    year: 2023,
    category: 'Sport',
    displacement: 659,
    power: 95,
    weight: 183,
    seatHeight: 820,
    licence: 'A',
    city: 'London',
    pickupArea: 'Shoreditch',
    pricePerDay: 74,
    weeklyDiscount: 0.14,
    monthlyDiscount: 0.28,
    deposit: 400,
    milesPerDay: 140,
    extraMileRate: 0.34,
    rating: 4.92,
    trips: 27,
    instantBook: true,
    host: { name: 'Reuben C.', since: 2022, topHost: false },
    listedFrom: -2,
    listedTo: 42,
    bookedOffsets: [[8, 11]],
    included: ['Cruise control', 'Tail pack', 'Paddock stand'],
    note: 'Half the weight of a litre bike and twice the fun below the speed limit. Cruise control is a gift on the M-way.'
  },
  {
    id: 'africa-twin',
    make: 'Honda',
    model: 'Africa Twin 1100',
    year: 2022,
    category: 'Adventure',
    displacement: 1084,
    power: 101,
    weight: 226,
    seatHeight: 850,
    licence: 'A',
    city: 'Edinburgh',
    pickupArea: 'Newington',
    pricePerDay: 98,
    weeklyDiscount: 0.2,
    monthlyDiscount: 0.36,
    deposit: 550,
    milesPerDay: 200,
    extraMileRate: 0.3,
    rating: 4.9,
    trips: 41,
    instantBook: true,
    host: { name: 'Struan G.', since: 2021, topHost: true },
    listedFrom: -4,
    listedTo: 64,
    bookedOffsets: [[25, 30]],
    included: ['Soft panniers', 'Centre stand', 'Knobbly tyres available'],
    note: 'DCT gearbox, so no clutch lever if that appeals. Will happily do 400 miles of Highland road in a day.'
  },
  {
    id: 'vstrom-650',
    make: 'Suzuki',
    model: 'V-Strom 650XT',
    year: 2020,
    category: 'Adventure',
    displacement: 645,
    power: 70,
    weight: 216,
    seatHeight: 835,
    licence: 'A',
    city: 'Brighton',
    pickupArea: 'North Laine',
    pricePerDay: 56,
    weeklyDiscount: 0.17,
    monthlyDiscount: 0.32,
    deposit: 250,
    milesPerDay: 175,
    extraMileRate: 0.28,
    rating: 4.87,
    trips: 57,
    instantBook: true,
    host: { name: 'Gita N.', since: 2020, topHost: true },
    listedFrom: -9,
    listedTo: 50,
    bookedOffsets: [],
    included: ['Givi top box', 'Taller screen', 'Heated grips'],
    note: 'Utterly unbreakable and 60mpg all day. Not glamorous, just the most useful bike I have owned.'
  },
  {
    id: 'bonneville-t120',
    make: 'Triumph',
    model: 'Bonneville T120',
    year: 2021,
    category: 'Classic',
    displacement: 1200,
    power: 78,
    weight: 236,
    seatHeight: 790,
    licence: 'A',
    city: 'Leeds',
    pickupArea: 'Chapel Allerton',
    pricePerDay: 72,
    weeklyDiscount: 0.15,
    monthlyDiscount: 0.3,
    deposit: 400,
    milesPerDay: 150,
    extraMileRate: 0.32,
    rating: 4.96,
    trips: 31,
    instantBook: false,
    host: { name: 'Will A.', since: 2022, topHost: true },
    listedFrom: 1,
    listedTo: 46,
    bookedOffsets: [],
    included: ['Bench seat', 'Brass badges', 'Waxed cotton roll bag'],
    note: 'Wedding-photo pretty and genuinely quick. Please do not leave it outside overnight.'
  }
];

/** Resolve the fleet against a given day. Pure — same `today` in, same fleet out. */
export function getFleet(today: ISODate): Bike[] {
  return SEEDS.map(({ listedFrom, listedTo, bookedOffsets, ...bike }) => ({
    ...bike,
    listed: { from: addDays(today, listedFrom), to: addDays(today, listedTo) } satisfies DateRange,
    booked: bookedOffsets.map(([from, to]) => ({ from: addDays(today, from), to: addDays(today, to) }))
  }));
}

export function getBike(today: ISODate, id: string): Bike | undefined {
  return getFleet(today).find((bike) => bike.id === id);
}

/** Cities with at least one listing, alphabetical. */
export const CITIES: string[] = [...new Set(SEEDS.map((s) => s.city))].sort();

/** Categories present in the fleet, in the order riders tend to shop them. */
export const CATEGORIES: Category[] = ['Sport', 'Naked', 'Adventure', 'Classic', 'Cruiser', 'Electric'];

export const FLEET_SIZE = SEEDS.length;

/** Cheapest and dearest daily rate — drives the price-filter bounds. */
export const PRICE_FLOOR = Math.min(...SEEDS.map((s) => s.pricePerDay));
export const PRICE_CEILING = Math.max(...SEEDS.map((s) => s.pricePerDay));
